# Generated by Django 3.2.9 on 2021-12-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bella_salon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=1000)),
                ('service', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
