# Generated by Django 3.2.9 on 2021-12-29 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bella_salon', '0002_auto_20211230_0443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service',
            new_name='service_name',
        ),
    ]
