# Generated by Django 3.2.9 on 2021-12-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bella_salon', '0004_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=1000)),
                ('method', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=100)),
            ],
        ),
    ]
